server:
  port:8082

spring:
  application:
    name: OrderService

  datasource:
    url: jdbc:mysql://localhost:3307/orderdb
    username: orderuser
    password: orderpass
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
      validation-timeout: 5000
      keepalive-time: 30000

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySql8Dialect


  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

logging:
  file:
    name: logs/order-service.log   # file will be created here
  level:
    root: INFO
    com.mfp.orderservice: DEBUG
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"





